stages:
  - build
  - test
  - docker-build

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./dist
  only:
    - master


test:
  stage: test
  script:
    - npm run lint
  only:
    - master

docker-build:
  stage: docker-build
  script:
    - docker build --platform linux/amd64 -t kirillshakhov/devops-frontend-image:$CI_COMMIT_SHORT_SHA .
    - docker push kirillshakhov/devops-frontend-image:$CI_COMMIT_SHORT_SHA
  only:
    - master
  dependencies:
    - build
