stages:
  - build

build_windows:
  stage: build
  variables:
    GOARCH: amd64
    GOOS: windows
    CGO_ENABLED: 0
  script:
    - npm install
    - npm run build
    - npm run lint
  artifacts:
    paths:
      - ./app_windows_amd64.exe
  only:
    - master

build_linux:
  stage: build
  variables:
    GOARCH: amd64
    GOOS: linux
    CGO_ENABLED: 0
  script:
    - npm install
    - npm run build
    - npm run lint
  artifacts:
    paths:
      - ./app_linux_amd64
  only:
    - master

build_mac:
  stage: build
  variables:
    GOARCH: amd64
    GOOS: darwin
    CGO_ENABLED: 0
  script:
    - npm install
    - npm run build
    - npm run lint
  artifacts:
    paths:
      - ./app_mac_amd64
  only:
    - master

build_mac_arm:
  stage: build
  variables:
    GOARCH: arm64
    GOOS: darwin
    CGO_ENABLED: 0
  script:
    - npm install
    - npm run build
    - npm run lint
  artifacts:
    paths:
      - ./app_mac_arm64
  only:
    - master
